version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    assignees:
      - ethancstuart
    labels:
      - dependencies
    groups:
      types:
        patterns:
          - "@types/*"
      testing:
        patterns:
          - "vitest"
          - "@testing-library/*"
          - "@playwright/*"
          - "playwright"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    assignees:
      - ethancstuart
    labels:
      - dependencies
      - ci
