import { createClient } from '@/lib/supabase/server'
import fs from 'fs/promises'
import path from 'path'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Transparency — Prototype Studio',
  description: 'Build costs, platform stats, and pipeline metrics. Full transparency.',
}

export const revalidate = 3600

interface BuildStats {
  loc: number
  files: number
  contentFiles: number
  tests: number
  routes: number
  commits: number
  generatedAt: string
}

export default async function TransparencyPage() {
  const supabase = await createClient()

  // Load build stats from file (generated by GitHub Action)
  let buildStats: BuildStats | null = null
  try {
    const raw = await fs.readFile(path.join(process.cwd(), 'build-stats.json'), 'utf-8')
    buildStats = JSON.parse(raw)
  } catch {
    // File doesn't exist yet — that's fine
  }

  // Platform costs
  const { data: costs } = await supabase
    .from('platform_costs')
    .select('*')
    .order('month', { ascending: false })

  const totalCostCents = (costs || []).reduce((sum, c) => sum + c.amount_cents, 0)

  // Pipeline metrics
  const { data: pipelineRuns } = await supabase
    .from('pipeline_runs')
    .select('status, total_tokens, total_cost_cents')

  const totalRuns = (pipelineRuns || []).length
  const successfulRuns = (pipelineRuns || []).filter((r) => r.status === 'completed').length
  const totalPipelineTokens = (pipelineRuns || []).reduce((sum, r) => sum + (r.total_tokens || 0), 0)
  const totalPipelineCost = (pipelineRuns || []).reduce((sum, r) => sum + (r.total_cost_cents || 0), 0)

  return (
    <div className="mx-auto max-w-4xl px-6 py-16">
      <div className="mb-12">
        <h1 className="mb-4 text-4xl font-bold tracking-tight text-[hsl(var(--fg))]">Transparency</h1>
        <p className="max-w-2xl text-lg text-[hsl(var(--fg-secondary))]">
          Full transparency on what it costs to build and run this platform.
          Every dollar, every token, every line of code.
        </p>
      </div>

      {/* Build Stats */}
      {buildStats && (
        <section className="mb-16">
          <h2 className="mb-6 text-2xl font-semibold text-[hsl(var(--fg))]">Build Stats</h2>
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
            <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
              <div className="text-2xl font-bold text-[hsl(var(--fg))]">{buildStats.loc?.toLocaleString()}</div>
              <div className="text-xs text-[hsl(var(--fg-muted))]">Lines of Code</div>
            </div>
            <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
              <div className="text-2xl font-bold text-[hsl(var(--fg))]">{buildStats.files}</div>
              <div className="text-xs text-[hsl(var(--fg-muted))]">Source Files</div>
            </div>
            <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
              <div className="text-2xl font-bold text-[hsl(var(--fg))]">{buildStats.contentFiles}</div>
              <div className="text-xs text-[hsl(var(--fg-muted))]">Content Files</div>
            </div>
            <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
              <div className="text-2xl font-bold text-[hsl(var(--fg))]">{buildStats.tests}</div>
              <div className="text-xs text-[hsl(var(--fg-muted))]">Tests</div>
            </div>
            <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
              <div className="text-2xl font-bold text-[hsl(var(--fg))]">{buildStats.routes}</div>
              <div className="text-xs text-[hsl(var(--fg-muted))]">Routes</div>
            </div>
            <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
              <div className="text-2xl font-bold text-[hsl(var(--fg))]">{buildStats.commits}</div>
              <div className="text-xs text-[hsl(var(--fg-muted))]">Commits</div>
            </div>
          </div>
          <p className="mt-2 text-xs text-[hsl(var(--fg-faint))]">
            Last updated:{' '}
            {buildStats.generatedAt
              ? new Date(buildStats.generatedAt).toLocaleDateString()
              : 'unknown'}
          </p>
        </section>
      )}

      {/* Pipeline Metrics */}
      <section className="mb-16">
        <h2 className="mb-6 text-2xl font-semibold text-[hsl(var(--fg))]">Pipeline Metrics</h2>
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
            <div className="text-2xl font-bold text-[hsl(var(--fg))]">{totalRuns}</div>
            <div className="text-xs text-[hsl(var(--fg-muted))]">Pipeline Runs</div>
          </div>
          <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
            <div className="text-2xl font-bold text-[hsl(var(--fg))]">
              {totalRuns > 0 ? Math.round((successfulRuns / totalRuns) * 100) : 0}%
            </div>
            <div className="text-xs text-[hsl(var(--fg-muted))]">Success Rate</div>
          </div>
          <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
            <div className="text-2xl font-bold text-[hsl(var(--fg))]">
              {totalPipelineTokens.toLocaleString()}
            </div>
            <div className="text-xs text-[hsl(var(--fg-muted))]">Tokens Used</div>
          </div>
          <div className="rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-4 text-center">
            <div className="text-2xl font-bold text-[hsl(var(--fg))]">
              ${(totalPipelineCost / 100).toFixed(2)}
            </div>
            <div className="text-xs text-[hsl(var(--fg-muted))]">Pipeline Cost</div>
          </div>
        </div>
      </section>

      {/* Platform Costs */}
      <section className="mb-16">
        <h2 className="mb-6 text-2xl font-semibold text-[hsl(var(--fg))]">Platform Costs</h2>
        <div className="mb-4 rounded-lg border border-[hsl(var(--border-base))] bg-[hsl(var(--bg-subtle))] p-6">
          <div className="text-3xl font-bold text-[hsl(var(--fg))]">${(totalCostCents / 100).toFixed(2)}</div>
          <div className="text-sm text-[hsl(var(--fg-muted))]">Total investment to date</div>
        </div>
        {costs && costs.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-[hsl(var(--border-base))] text-left text-xs text-[hsl(var(--fg-muted))]">
                  <th className="pb-2">Month</th>
                  <th className="pb-2">Category</th>
                  <th className="pb-2 text-right">Amount</th>
                  <th className="pb-2">Notes</th>
                </tr>
              </thead>
              <tbody>
                {costs.map((cost) => (
                  <tr key={cost.id} className="border-b border-[hsl(var(--border-base))]">
                    <td className="py-2 text-sm text-[hsl(var(--fg-secondary))]">{cost.month}</td>
                    <td className="py-2 text-sm text-[hsl(var(--fg-muted))]">{cost.category}</td>
                    <td className="py-2 text-right text-sm text-[hsl(var(--fg-secondary))]">
                      ${(cost.amount_cents / 100).toFixed(2)}
                    </td>
                    <td className="py-2 text-sm text-[hsl(var(--fg-faint))]">{cost.notes || ''}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p className="text-sm text-[hsl(var(--fg-faint))]">No cost data entered yet.</p>
        )}
      </section>
    </div>
  )
}
